[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
color-eyre = "0.6.2"
geo = "0.27.0"
itertools = "0.12.0"
num-traits = "0.2.17"
pathfinding = "4.4.0"
rayon = "1.8.0"
